global: 
    objetoBD: contacto
    nombre_general: 
        nombres 
        apellidos
filtros: 
    estado_id:
        tipo: lm_mul
        lbl: lbl_estado
        lista_maestra: estado
        general: true
    asesor_id: 
        tipo: relacionado_mul
        tabla_db: usuario
        lbl: lbl_asesor_asignado
        select_consulta: CONCAT(nombres," ",apellidos)
        condicional_consulta: ''
    cuenta_id: 
        tipo: relacionado_mul
        tabla_db: cuenta
        lbl: lbl_cuenta
        select_consulta: IFNULL(nombres,nombre_comercial)
        condicional_consulta: ''
    cargo: 
        tipo: txt
        lbl: lbl_cargo